<a href="https://colab.research.google.com/github/AvaneSauhard/Biometric/blob/main/Authentication_ex_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing libraries
from google.colab import drive
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
import keras
from tensorflow.keras.utils import to_categorical
from sklearn.utils import resample
import itertools
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import DetCurveDisplay, RocCurveDisplay

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#read CSV File
P4_0 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s01_ex05.xlsx",header=None)
P4_1 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s02_ex05.xlsx",header=None)
P4_2 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s03_ex05.xlsx",header=None)
P4_3 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s04_ex05.xlsx",header=None)
P4_4 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s05_ex05.xlsx",header=None)
P4_5 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s06_ex05.xlsx",header=None)
P4_6 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s07_ex05.xlsx",header=None)
P4_7 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s08_ex05.xlsx",header=None)
P4_8 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s09_ex05.xlsx",header=None)
P4_9 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s10_ex05.xlsx",header=None)
P4_10 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s11_ex05.xlsx",header=None)
P4_11 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s12_ex05.xlsx",header=None)
P4_12 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s13_ex05.xlsx",header=None)
P4_13 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s14_ex05.xlsx",header=None)
P4_14 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s15_ex05.xlsx",header=None)
P4_15 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s16_ex05.xlsx",header=None)
P4_16 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s17_ex05.xlsx",header=None)
P4_17 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s18_ex05.xlsx",header=None)
P4_18 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s19_ex05.xlsx",header=None)
P4_19 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/P4_s20_ex05.xlsx",header=None)




In [ ]:
#read CSV File
Cz_0 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s01_ex05.xlsx",header=None)
Cz_1 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s02_ex05.xlsx",header=None)
Cz_2 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s03_ex05.xlsx",header=None)
Cz_3 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s04_ex05.xlsx",header=None)
Cz_4 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s05_ex05.xlsx",header=None)
Cz_5 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s06_ex05.xlsx",header=None)
Cz_6 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s07_ex05.xlsx",header=None)
Cz_7 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s08_ex05.xlsx",header=None)
Cz_8 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s09_ex05.xlsx",header=None)
Cz_9 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s10_ex05.xlsx",header=None)
Cz_10 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s11_ex05.xlsx",header=None)
Cz_11 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s12_ex05.xlsx",header=None)
Cz_12 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s13_ex05.xlsx",header=None)
Cz_13 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s14_ex05.xlsx",header=None)
Cz_14 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s15_ex05.xlsx",header=None)
Cz_15 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s16_ex05.xlsx",header=None)
Cz_16 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s17_ex05.xlsx",header=None)
Cz_17 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s18_ex05.xlsx",header=None)
Cz_18 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s19_ex05.xlsx",header=None)
Cz_19 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/Cz_s20_ex05.xlsx",header=None)




In [ ]:
F8_0 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s01_ex05.xlsx",header=None)
F8_1 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s02_ex05.xlsx",header=None)
F8_2 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s03_ex05.xlsx",header=None)
F8_3 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s04_ex05.xlsx",header=None)
F8_4 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s05_ex05.xlsx",header=None)
F8_5 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s06_ex05.xlsx",header=None)
F8_6 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s07_ex05.xlsx",header=None)
F8_7 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s08_ex05.xlsx",header=None)
F8_8 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s09_ex05.xlsx",header=None)
F8_9 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s10_ex05.xlsx",header=None)
F8_10 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s11_ex05.xlsx",header=None)
F8_11 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s12_ex05.xlsx",header=None)
F8_12 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s13_ex05.xlsx",header=None)
F8_13 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s14_ex05.xlsx",header=None)
F8_14 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s15_ex05.xlsx",header=None)
F8_15 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s16_ex05.xlsx",header=None)
F8_16 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s17_ex05.xlsx",header=None)
F8_17 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s18_ex05.xlsx",header=None)
F8_18 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s19_ex05.xlsx",header=None)
F8_19 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/F8_s20_ex05.xlsx",header=None)

In [ ]:
#read CSV File
T7_0 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s01_ex05.xlsx",header=None)
T7_1 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s02_ex05.xlsx",header=None)
T7_2 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s03_ex05.xlsx",header=None)
T7_3 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s04_ex05.xlsx",header=None)
T7_4 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s05_ex05.xlsx",header=None)
T7_5 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s06_ex05.xlsx",header=None)
T7_6 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s07_ex05.xlsx",header=None)
T7_7 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s08_ex05.xlsx",header=None)
T7_8 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s09_ex05.xlsx",header=None)
T7_9 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s10_ex05.xlsx",header=None)
T7_10 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s11_ex05.xlsx",header=None)
T7_11 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s12_ex05.xlsx",header=None)
T7_12 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s13_ex05.xlsx",header=None)
T7_13 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s14_ex05.xlsx",header=None)
T7_14 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s15_ex05.xlsx",header=None)
T7_15 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s16_ex05.xlsx",header=None)
T7_16 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s17_ex05.xlsx",header=None)
T7_17 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s18_ex05.xlsx",header=None)
T7_18 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s19_ex05.xlsx",header=None)
T7_19 = pd.read_excel("/content/drive/MyDrive/exp_510/ex_05/T7_s20_ex05.xlsx",header=None)




In [ ]:
print(f'0:{P4_0.shape[0]}')
print(f'1:{P4_1.shape[0]}')
print(f'2:{P4_2.shape[0]}')
print(f'3:{P4_3.shape[0]}')
print(f'4:{P4_4.shape[0]}')
print(f'5:{P4_5.shape[0]}')
print(f'6:{P4_6.shape[0]}')
print(f'7:{P4_7.shape[0]}')
print(f'8:{P4_8.shape[0]}')
print(f'9:{P4_9.shape[0]}')
print(f'10:{P4_10.shape[0]}')
print(f'11:{P4_11.shape[0]}')
print(f'12:{P4_12.shape[0]}')
print(f'13:{P4_13.shape[0]}')
print(f'14:{P4_14.shape[0]}')
print(f'15:{P4_15.shape[0]}')
print(f'16:{P4_16.shape[0]}')
print(f'17:{P4_17.shape[0]}')
print(f'18:{P4_18.shape[0]}')
print(f'19:{P4_19.shape[0]}')

0:30
1:30
2:30
3:30
4:50
5:30
6:30
7:30
8:30
9:30
10:30
11:30
12:30
13:30
14:30
15:30
16:30
17:30
18:30
19:30


In [ ]:
import random
values = list()
for i in range(0,20):
  values.append(random.randrange(30))
values

[6, 18, 28, 8, 9, 9, 9, 17, 14, 20, 3, 0, 23, 16, 6, 22, 6, 22, 9, 9]

In [ ]:
P4_0.iloc[[values[0]]].shape

(1, 801)

In [ ]:
P4_0 = P4_0.iloc[:,:-1]
P4_1 = P4_1.iloc[:,:-1]
P4_2 = P4_2.iloc[:,:-1]
P4_3 = P4_3.iloc[:,:-1]
P4_4 = P4_4.iloc[:,:-1]
P4_5 = P4_5.iloc[:,:-1]
P4_6 = P4_6.iloc[:,:-1]
P4_7 = P4_7.iloc[:,:-1]
P4_8 = P4_8.iloc[:,:-1]
P4_9 = P4_9.iloc[:,:-1]
P4_10 = P4_10.iloc[:,:-1]
P4_11 = P4_11.iloc[:,:-1]
P4_12 = P4_12.iloc[:,:-1]
P4_13 = P4_13.iloc[:,:-1]
P4_14 = P4_14.iloc[:,:-1]
P4_15 = P4_15.iloc[:,:-1]
P4_16 = P4_16.iloc[:,:-1]
P4_17 = P4_17.iloc[:,:-1]
P4_18 = P4_18.iloc[:,:-1]
P4_19 = P4_19.iloc[:,:-1]

F8_0 = F8_0.iloc[:,:-1]
F8_1 = F8_1.iloc[:,:-1]
F8_2 = F8_2.iloc[:,:-1]
F8_3 = F8_3.iloc[:,:-1]
F8_4 = F8_4.iloc[:,:-1]
F8_5 = F8_5.iloc[:,:-1]
F8_6 = F8_6.iloc[:,:-1]
F8_7 = F8_7.iloc[:,:-1]
F8_8 = F8_8.iloc[:,:-1]
F8_9 = F8_9.iloc[:,:-1]
F8_10 = F8_10.iloc[:,:-1]
F8_11 = F8_11.iloc[:,:-1]
F8_12 = F8_12.iloc[:,:-1]
F8_13 = F8_13.iloc[:,:-1]
F8_14 = F8_14.iloc[:,:-1]
F8_15 = F8_15.iloc[:,:-1]
F8_16 = F8_16.iloc[:,:-1]
F8_17 = F8_17.iloc[:,:-1]
F8_18 = F8_18.iloc[:,:-1]
F8_19 = F8_19.iloc[:,:-1]

Cz_0 = Cz_0.iloc[:,:-1]
Cz_1 = Cz_1.iloc[:,:-1]
Cz_2 = Cz_2.iloc[:,:-1]
Cz_3 = Cz_3.iloc[:,:-1]
Cz_4 = Cz_4.iloc[:,:-1]
Cz_5 = Cz_5.iloc[:,:-1]
Cz_6 = Cz_6.iloc[:,:-1]
Cz_7 = Cz_7.iloc[:,:-1]
Cz_8 = Cz_8.iloc[:,:-1]
Cz_9 = Cz_9.iloc[:,:-1]
Cz_10 = Cz_10.iloc[:,:-1]
Cz_11 = Cz_11.iloc[:,:-1]
Cz_12 = Cz_12.iloc[:,:-1]
Cz_13 = Cz_13.iloc[:,:-1]
Cz_14 = Cz_14.iloc[:,:-1]
Cz_15 = Cz_15.iloc[:,:-1]
Cz_16 = Cz_16.iloc[:,:-1]
Cz_17 = Cz_17.iloc[:,:-1]
Cz_18 = Cz_18.iloc[:,:-1]
Cz_19 = Cz_19.iloc[:,:-1]

T7_0 = T7_0.iloc[:,:-1]
T7_1 = T7_1.iloc[:,:-1]
T7_2 = T7_2.iloc[:,:-1]
T7_3 = T7_3.iloc[:,:-1]
T7_4 = T7_4.iloc[:,:-1]
T7_5 = T7_5.iloc[:,:-1]
T7_6 = T7_6.iloc[:,:-1]
T7_7 = T7_7.iloc[:,:-1]
T7_8 = T7_8.iloc[:,:-1]
T7_9 = T7_9.iloc[:,:-1]
T7_10 = T7_10.iloc[:,:-1]
T7_11 = T7_11.iloc[:,:-1]
T7_12 = T7_12.iloc[:,:-1]
T7_13 = T7_13.iloc[:,:-1]
T7_14 = T7_14.iloc[:,:-1]
T7_15 = T7_15.iloc[:,:-1]
T7_16 = T7_16.iloc[:,:-1]
T7_17 = T7_17.iloc[:,:-1]
T7_18 = T7_18.iloc[:,:-1]
T7_19 = T7_19.iloc[:,:-1]

In [ ]:
P4_0_test=P4_0.iloc[[values[0]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_1_test=P4_1.iloc[[values[1]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_2_test=P4_2.iloc[[values[2]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_3_test=P4_3.iloc[[values[3]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_4_test=P4_4.iloc[[values[4]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_5_test=P4_5.iloc[[values[5]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_6_test=P4_6.iloc[[values[6]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_7_test=P4_7.iloc[[values[7]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_8_test=P4_8.iloc[[values[8]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_9_test=P4_9.iloc[[values[9]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_10_test=P4_10.iloc[[values[10]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_11_test=P4_11.iloc[[values[11]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_12_test=P4_12.iloc[[values[12]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_13_test=P4_13.iloc[[values[13]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_14_test=P4_14.iloc[[values[14]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_15_test=P4_15.iloc[[values[15]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_16_test=P4_16.iloc[[values[16]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_17_test=P4_17.iloc[[values[17]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_18_test=P4_18.iloc[[values[18]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
P4_19_test=P4_19.iloc[[values[19]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)


F8_0_test=F8_0.iloc[[values[0]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_1_test=F8_1.iloc[[values[1]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_2_test=F8_2.iloc[[values[2]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_3_test=F8_3.iloc[[values[3]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_4_test=F8_4.iloc[[values[4]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_5_test=F8_5.iloc[[values[5]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_6_test=F8_6.iloc[[values[6]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_7_test=F8_7.iloc[[values[7]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_8_test=F8_8.iloc[[values[8]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_9_test=F8_9.iloc[[values[9]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_10_test=F8_10.iloc[[values[10]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_11_test=F8_11.iloc[[values[11]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_12_test=F8_12.iloc[[values[12]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_13_test=F8_13.iloc[[values[13]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_14_test=F8_14.iloc[[values[14]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_15_test=F8_15.iloc[[values[15]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_16_test=F8_16.iloc[[values[16]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_17_test=F8_17.iloc[[values[17]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_18_test=F8_18.iloc[[values[18]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
F8_19_test=F8_19.iloc[[values[19]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)


T7_0_test=T7_0.iloc[[values[0]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_1_test=T7_1.iloc[[values[1]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_2_test=T7_2.iloc[[values[2]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_3_test=T7_3.iloc[[values[3]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_4_test=T7_4.iloc[[values[4]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_5_test=T7_5.iloc[[values[5]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_6_test=T7_6.iloc[[values[6]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_7_test=T7_7.iloc[[values[7]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_8_test=T7_8.iloc[[values[8]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_9_test=T7_9.iloc[[values[9]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_10_test=T7_10.iloc[[values[10]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_11_test=T7_11.iloc[[values[11]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_12_test=T7_12.iloc[[values[12]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_13_test=T7_13.iloc[[values[13]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_14_test=T7_14.iloc[[values[14]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_15_test=T7_15.iloc[[values[15]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_16_test=T7_16.iloc[[values[16]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_17_test=T7_17.iloc[[values[17]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_18_test=T7_18.iloc[[values[18]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
T7_19_test=T7_19.iloc[[values[19]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)


Cz_0_test=Cz_0.iloc[[values[0]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_1_test=Cz_1.iloc[[values[1]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_2_test=Cz_2.iloc[[values[2]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_3_test=Cz_3.iloc[[values[3]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_4_test=Cz_4.iloc[[values[4]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_5_test=Cz_5.iloc[[values[5]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_6_test=Cz_6.iloc[[values[6]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_7_test=Cz_7.iloc[[values[7]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_8_test=Cz_8.iloc[[values[8]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_9_test=Cz_9.iloc[[values[9]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_10_test=Cz_10.iloc[[values[10]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_11_test=Cz_11.iloc[[values[11]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_12_test=Cz_12.iloc[[values[12]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_13_test=Cz_13.iloc[[values[13]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_14_test=Cz_14.iloc[[values[14]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_15_test=Cz_15.iloc[[values[15]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_16_test=Cz_16.iloc[[values[16]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_17_test=Cz_17.iloc[[values[17]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_18_test=Cz_18.iloc[[values[18]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)
Cz_19_test=Cz_19.iloc[[values[19]]]+0.2*np.random.normal(0,1,size = P4_0.iloc[[values[0]]].shape)


In [ ]:
# we add the class label to each file 

P4_0_test[800] = 0
F8_0_test[800] = 0
Cz_0_test[800] = 0
T7_0_test[800] = 0

P4_1_test[800] = 1
F8_1_test[800] = 1
Cz_1_test[800] = 1
T7_1_test[800] = 1

P4_2_test[800] = 2
F8_2_test[800] = 2
Cz_2_test[800] = 2
T7_2_test[800] = 2

P4_3_test[800] = 3
F8_3_test[800] = 3
Cz_3_test[800] = 3
T7_3_test[800] = 3

P4_4_test[800] = 4
F8_4_test[800] = 4
Cz_4_test[800] = 4
T7_4_test[800] = 4

P4_5_test[800] = 5
F8_5_test[800] = 5
Cz_5_test[800] = 5
T7_5_test[800] = 5

P4_6_test[800] = 6
F8_6_test[800] = 6
Cz_6_test[800] = 6
T7_6_test[800] = 6

P4_7_test[800] = 7
F8_7_test[800] = 7
Cz_7_test[800] = 7
T7_7_test[800] = 7

P4_8_test[800] = 8
F8_8_test[800] = 8
Cz_8_test[800] = 8
T7_8_test[800] = 8

P4_9_test[800] = 9
F8_9_test[800] = 9
Cz_9_test[800] = 9
T7_9_test[800] = 9

P4_10_test[800] = 10
F8_10_test[800] = 10
Cz_10_test[800] = 10
T7_10_test[800] = 10

P4_11_test[800] = 11
F8_11_test[800] = 11
Cz_11_test[800] = 11
T7_11_test[800] = 11

P4_12_test[800] = 12
F8_12_test[800] = 12
Cz_12_test[800] = 12
T7_12_test[800] = 12

P4_13_test[800] = 13
F8_13_test[800] = 13
Cz_13_test[800] = 13
T7_13_test[800] = 13

P4_14_test[800] = 14
F8_14_test[800] = 14
Cz_14_test[800] = 14
T7_14_test[800] = 14

P4_15_test[800] = 15
F8_15_test[800] = 15
Cz_15_test[800] = 15
T7_15_test[800] = 15

P4_16_test[800] = 16
F8_16_test[800] = 16
Cz_16_test[800] = 16
T7_16_test[800] = 16

P4_17_test[800] = 17
F8_17_test[800] = 17
Cz_17_test[800] = 17
T7_17_test[800] = 17

P4_18_test[800] = 18
F8_18_test[800] = 18
Cz_18_test[800] = 18
T7_18_test[800] = 18

P4_19_test[800] = 19
F8_19_test[800] = 19
Cz_19_test[800] = 19
T7_19_test[800] = 19
#AF7_0[11364] = 0
#AF8_0[11364] = 0
#TP9_0[11364] = 0
#TP10_0[11364] = 0

#AF7_1[11364] = 1
#AF8_1[11364] = 1
#TP9_1[11364] = 1
#TP10_1[11364] = 1

#AF7_2[11364] = 2
#AF8_2[11364] = 2
#TP9_2[11364] = 2
#TP10_2[11364] = 2



In [ ]:
P4_test = pd.concat([P4_0_test, P4_1_test, P4_2_test,P4_3_test, P4_4_test, P4_5_test, P4_6_test, P4_7_test, P4_8_test, P4_9_test, P4_10_test, P4_11_test, P4_12_test, P4_13_test, P4_14_test, P4_15_test, P4_16_test, P4_17_test, P4_18_test, P4_19_test], axis=0, sort= False, ignore_index= True)
# test data is conactenated
Cz_test = pd.concat([Cz_0_test, Cz_1_test, Cz_2_test,Cz_3_test, Cz_4_test, Cz_5_test, Cz_6_test, Cz_7_test, Cz_8_test, Cz_9_test, Cz_10_test, Cz_11_test, Cz_12_test, Cz_13_test, Cz_14_test, Cz_15_test, Cz_16_test, Cz_17_test, Cz_18_test, Cz_19_test], axis=0, sort= False, ignore_index= True)
# test data is conactenated
F8_test = pd.concat([F8_0_test, F8_1_test, F8_2_test,F8_3_test, F8_4_test, F8_5_test, F8_6_test, F8_7_test, F8_8_test, F8_9_test, F8_10_test, F8_11_test, F8_12_test, F8_13_test, F8_14_test, F8_15_test, F8_16_test, F8_17_test, F8_18_test, F8_19_test], axis=0, sort= False, ignore_index= True)
# test data is conactenated
T7_test = pd.concat([T7_0_test, T7_1_test, T7_2_test,T7_3_test, T7_4_test, T7_5_test, T7_6_test, T7_7_test, T7_8_test, T7_9_test, T7_10_test, T7_11_test, T7_12_test, T7_13_test, T7_14_test, T7_15_test, T7_16_test, T7_17_test, T7_18_test, T7_19_test], axis=0, sort= False, ignore_index= True)


In [ ]:

test_data = [P4_test,Cz_test,F8_test,T7_test]

In [ ]:
# dstack function to add each channel one over the other i.e in 3rd dimension

test_data = np.dstack(test_data)

In [ ]:
test_data.shape

(20, 801, 4)

In [ ]:
# creating labels

target_test = test_data[:,800,0]

In [ ]:
test_data

array([[[  0.64,  -1.17,   1.99,   1.53],
        [  2.6 ,  -0.4 ,  -0.26,   3.93],
        [  0.53,  -1.42,  -3.27,   4.77],
        ...,
        [ -0.72,  -3.43,   4.9 ,  -0.1 ],
        [ -1.64,  -3.32,   3.73,   0.55],
        [  0.  ,   0.  ,   0.  ,   0.  ]],

       [[ 11.34,   1.13,  -8.76,   1.65],
        [ 12.37,   3.53,  -8.28,   0.05],
        [ 13.01,   6.33,  -6.96,  -0.6 ],
        ...,
        [  1.37,   4.17,   2.96,   3.82],
        [ -0.13,   6.14,   5.22,   5.18],
        [  1.  ,   1.  ,   1.  ,   1.  ]],

       [[  0.48,   2.09,   3.18,  -2.38],
        [ -1.21,   0.17,  -0.87,  -4.08],
        [ -2.44,   0.71,  -0.85,  -3.93],
        ...,
        [-12.51,  -1.3 ,   1.71,  -0.03],
        [-10.4 ,  -0.47,   1.86,  -4.48],
        [  2.  ,   2.  ,   2.  ,   2.  ]],

       ...,

       [[ -1.05,   4.71,  -2.86,  11.19],
        [  0.12,   3.67,  -3.14,   9.89],
        [  1.55,   2.28,  -2.8 ,   7.94],
        ...,
        [ 10.66,   1.1 ,   7.85,   0.77],
     

In [ ]:
target_test

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:

y_test = to_categorical(target_test)
# removing last column

x_test = test_data[:, :-1,:]


x_test = x_test.reshape(len(x_test), x_test.shape[1],4)

x_test.shape

(20, 800, 4)

In [ ]:
y_test

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [ ]:
from tensorflow import keras
model = keras.models.load_model('/content/drive/MyDrive/exp_510/ex_05/')
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 793, 64)           2112      
                                                                 
 batch_normalization (BatchN  (None, 793, 64)          256       
 ormalization)                                                   
                                                                 
 max_pooling1d (MaxPooling1D  (None, 791, 64)          0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 784, 128)          65664     
                                                                 
 batch_normalization_1 (Batc  (None, 784, 128)         512       
 hNormalization)                                                 
                                                        

In [ ]:
y_test.shape

(20, 20)

In [ ]:
loss,accuracy = model.evaluate(x_test,y_test)
print('Loss=',loss)
print('Accuracy=',accuracy)

1/1 [==============================] - 0s 236ms/step - loss: 1.4242 - accuracy: 0.8500
Loss= 1.4241650104522705
Accuracy= 0.8500000238418579


In [ ]:
P = model.predict(x_test)
print('P=',P)
print('shape of P=',P.shape)


1/1 [==============================] - 0s 152ms/step
P= [[1.00e+00 5.07e-32 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  3.51e-33 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.28e-38 0.00e+00
  0.00e+00 1.53e-11 0.00e+00 0.00e+00]
 [0.00e+00 5.75e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 3.57e-35 9.99e-01
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  1.30e-17 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.66e-32 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [9.26e-16 0.00e+00 0.00e+00 4.08e-33 1.07e-07 1.38e-28 4.17e-35 3.76e-09
  1.02e-25 2.91e-18 0.00e+00 0.00e+00 5.30e-26 0.00e+00 1.00e+00 3.82e-15
  0.00e+00 5.71e-36 4.67e-09 0.00e+00]
 [0.00e+0

In [ ]:
# converting prediction to classes
y_pred = np.argmax(P, axis=1)
print('shape of y_pred=',y_pred.shape)

shape of y_pred= (20,)


In [ ]:
y_test = np.argmax(y_test, axis=1)
print('shape of y_test=', y_test.shape)



shape of y_test= (20,)


In [ ]:
cm = confusion_matrix(y_test, y_pred)

In [ ]:
np.set_printoptions(precision=2)
print(cm)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [ ]:
cm_df = pd.DataFrame(cm, columns= ['PREDICTED 0', 'PREDICTED 1', 'PREDICTED 2', 'PREDICTED 3', 'PREDICTED 4', 'PREDICTED 5', 'PREDICTED 6', 'PREDICTED 7', 'PREDICTED 8', 'PREDICTED 9','PREDICTED 10', 'PREDICTED 11', 'PREDICTED 12', 'PREDICTED 13', 'PREDICTED 14', 'PREDICTED 15','PREDICTED 16', 'PREDICTED 17', 'PREDICTED 18', 'PREDICTED 19' ], index = ['ACTUAL 0', 'ACTUAL 1', 'ACTUAL 2','ACTUAL 3', 'ACTUAL 4', 'ACTUAL 5', 'ACTUAL 6', 'ACTUAL 7', 'ACTUAL 8', 'ACTUAL 9', 'ACTUAL 10', 'ACTUAL 11', 'ACTUAL 12', 'ACTUAL 13', 'ACTUAL 14','ACTUAL 15', 'ACTUAL 16', 'ACTUAL 17', 'ACTUAL 18', 'ACTUAL 19' ])

In [ ]:
cm_df

PREDICTED 0  PREDICTED 1  PREDICTED 2  PREDICTED 3  PREDICTED 4  \
ACTUAL 0             1            0            0            0            0   
ACTUAL 1             0            0            0            0            0   
ACTUAL 2             0            0            1            0            0   
ACTUAL 3             0            0            0            1            0   
ACTUAL 4             0            0            0            0            0   
ACTUAL 5             0            0            0            0            0   
ACTUAL 6             0            0            0            0            0   
ACTUAL 7             0            0            0            0            0   
ACTUAL 8             0            0            0            0            0   
ACTUAL 9             0            0            0            0            0   
ACTUAL 10            0            0            0            0            0   
ACTUAL 11            0            0            0            0            0   
ACTUAL 12            0            0            0            0            0   
ACTUAL 13            0            0            0            0            0   
ACTUAL 14            0            0            0            0            0   
ACTUAL 15            0            0            0            0            0   
ACTUAL 16            0            0            0            0            0   
ACTUAL 17            0            0            0            0            0   
ACTUAL 18            0            0            0            0            0   
ACTUAL 19            0            0            0            0            0   

           PREDICTED 5  PREDICTED 6  PREDICTED 7  PREDICTED 8  PREDICTED 9  \
ACTUAL 0             0            0            0            0            0   
ACTUAL 1             0            0            1            0            0   
ACTUAL 2             0            0            0            0            0   
ACTUAL 3             0            0            0            0            0   
ACTUAL 4             0            0            0            0            0   
ACTUAL 5             0            0            0            0            0   
ACTUAL 6             0            1            0            0            0   
ACTUAL 7             0            0            1            0            0   
ACTUAL 8             0            0            0            1            0   
ACTUAL 9             0            0            0            0            1   
ACTUAL 10            0            0            0            0            0   
ACTUAL 11            0            0            0            0            0   
ACTUAL 12            0            0            0            0            0   
ACTUAL 13            0            0            0            0            0   
ACTUAL 14            0            0            0            0            0   
ACTUAL 15            0            0            0            0            0   
ACTUAL 16            0            0            0            0            0   
ACTUAL 17            0            0            0            0            0   
ACTUAL 18            0            0            0            0            0   
ACTUAL 19            0            0            0            0            0   

           PREDICTED 10  PREDICTED 11  PREDICTED 12  PREDICTED 13  \
ACTUAL 0              0             0             0             0   
ACTUAL 1              0             0             0             0   
ACTUAL 2              0             0             0             0   
ACTUAL 3              0             0             0             0   
ACTUAL 4              0             0             0             0   
ACTUAL 5              0             1             0             0   
ACTUAL 6              0             0             0             0   
ACTUAL 7              0             0             0             0   
ACTUAL 8              0             0             0             0   
ACTUAL 9              0             0      

In [ ]:
from statistics import mean

frrs = list(0 for x in range(0, 20))
fars = list(0 for x in range(0, 20))
#(test, pred)
total=0
#print(cm[4,:])
for s in range(0, 20):
    #print("Class")
    #prin
    #label 
    TP = cm[s,s]
    FP = sum(cm[:,s]) - TP
   
    FN = sum(cm[s,:])-TP
    TN = sum(sum(cm))-TP-FP-FN
    #print(TP)
    #print(FP)
    #print(FN)
    ##print(TN)
    
    #print("cnt1")
    #print(cnt1)
    if (FP+TN)!=0:
     farTemp = FP/(FP+TN) 
     
     fars.append(farTemp)
    if (TP+FN)!=0: 
     frrTemp = FN/(TP+FN)
     frrs.append(frrTemp)
    #print(frrTemp)
    

FRR_mean = mean(frrs)#false match rate
FAR_mean = mean(fars)#false non match rate
eer = (FRR_mean + FAR_mean)/2
print("FAR:",FAR_mean)
print("FRR:",FRR_mean)
print("EER:",eer)

FAR: 0.003947368421052632
FRR: 0.075
EER: 0.039473684210526314


In [ ]:
#parameter calculation is performed
def multi_class_parameters(conf_matrix):
  
  ACC = (sum(conf_matrix.diagonal())/sum(sum(conf_matrix)))
  MC = 1-ACC
  [row, col]= conf_matrix.shape
  if(row>2):
    PR = [None] * row
    RC = [None] * row
    F1 = [None] * row
    SP = [None] * row
    ind = list(range(0,row))
    for cm in range(0,row):
      TN = None
      ind = list(range(0,row))
      PR[cm] = conf_matrix[cm,cm]/(conf_matrix[:,cm]).sum()
      RC[cm] = conf_matrix[cm,cm]/(conf_matrix[cm,:]).sum()
      F1[cm] = (2*(PR[cm])*(RC[cm]))/((PR[cm])+(RC[cm]))
      ind.pop(cm)
      TN = (conf_matrix[np.ix_(ind,ind)]).sum()
      SP[cm] = TN/(conf_matrix[ind,:]).sum()

    Avg_RC =sum(RC)/row
    Avg_SP = sum(SP)/row
    Avg_PR = sum(PR)/row
    Avg_F1 = sum(F1)/row
    print('1. Accuracy:',ACC)
    print('2. Mis_classification:', MC)
    print('3. Sensitivity (Recall):',Avg_RC)
    print('4. specificity:',Avg_SP)
    print('5. Precision:',Avg_PR)
    print('6. F_1 Score:',Avg_F1)
  else:
    TP = conf_matrix[1][1]
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    MC = 1-ACC
    ACC = (float(TP+TN)/float(TP+TN+FP+FN))
    RC = (TP/ float(TP+TN))
    SP = (TN/ float(TN+TF))
    PR = (TP/float(TP+FP))
    F1 = 2*((PR*RC)/(PR+RC))
    print('1. Accuracy:',ACC)
    print('2. Mis_classification:', MC)
    print('3. Sensitivity (Recall):',Avg_RC)
    print('4. specificity:',Avg_SP)
    print('5. Precision:',Avg_PR)
    print('6. F_1 Score:',Avg_F1)
multi_class_parameters(cm)





1. Accuracy: 0.85
2. Mis_classification: 0.15000000000000002
3. Sensitivity (Recall): 0.85
4. specificity: 0.9921052631578948
5. Precision: nan
6. F_1 Score: nan


<ipython-input-66-3cfd7f1535c9>:16: RuntimeWarning: invalid value encountered in long_scalars
  PR[cm] = conf_matrix[cm,cm]/(conf_matrix[:,cm]).sum()
